Rails_Projects/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get 'signup' => 'users#new'
  # post 'users' => 'users#create'
  resources :users, except: [:new]
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # Defines the root path route ("/")
end

Rails_Projects/alpha-blog/app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 20, maximum: 200}
end

Rails_Projects/alpha-blog/app/models/user.rb
class User < ApplicationRecord
    mount_uploader :avatar, AvatarUploader

    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy

    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 4, maximum: 25 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

Rails_Projects/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id] 
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = 'You must be logged in.'
            redirect_to login_path
        end
    end

end

Rails_Projects/alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 2)
    end


    def show
    end


    def new
        @article = Article.new
    end


    def edit
    end


    def create
        # render plain: params[:article]
        @article = Article.new(article_params)
        @article.user = current_user
        # render plain: @article.inspect
        if @article.save
        # redirect_to article_path(@article)
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
            render 'new', status: :unprocessable_entity
        end
    end


    def update
        if @article.update(article_params)
          flash[:notice] = "Article was updated successfully."
          redirect_to @article
        else
          render 'edit', status: :unprocessable_entity
        end
    end


    def destroy
        @article.destroy
        redirect_to articles_path
    end


    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

    def require_same_user
        if current_user != @article.user
            flash[:alert] = "You cannot edit/delete other user\'s article"
            redirect_to @article
        end
    end

end

Rails_Projects/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
    end

end

Rails_Projects/alpha-blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = 'Logged in'
            redirect_to user
        else
            flash.now[:alert] = 'Email or Password was incorrect'
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = 'Logged Out'
        redirect_to root_path
    end

end

Rails_Projects/alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end


    def show
        @articles = @user.articles
    end

    
    def index
        @users = User.paginate(page: params[:page], per_page: 2)
    end


    def edit
    end


    def create
        # render plain: params[:article]
        @user = User.new(user_params)
        # render plain: @article.inspect
        if @user.save
        # redirect_to article_path(@article)
            session[:user_id] = @user.id
            flash[:notice] = "User Sign up successfull, Welcome #{@user.username}."
            redirect_to articles_path
        else
            render 'new', status: :unprocessable_entity
        end
    end


    def update
        if @user.update(user_params)
          flash[:notice] = "User was updated successfully."
          redirect_to @user
        else
          render 'edit', status: :unprocessable_entity
        end
    end


    def destroy
        @user.destroy
        session[:user_id] = nil
        flash[:alert] = "Account & associated articles deleted."
        redirect_to articles_path
    end

    private

    def set_user
        @user = User.find(params[:id])
    end


    def user_params
        params.require(:user).permit(:username, :email, :password, :f_name, :l_name, :avatar)
    end

    def require_same_user
        if current_user != @user
            flash[:alert] = "You cannot edit/delete other user\'s profile"
            redirect_to @user
        end
    end


end

Rails_Projects/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
      end


      def logged_in?
        !!current_user
      end

end

Rails_Projects/alpha-blog/app/views/articles/_article.html.erb
<table>

  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Written By</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>

    <tr>
      <td> <%= article.title %> </td>
      <td> <%= article.description %> </td>
      <td> <%= link_to article.user.username, user_path(article.user) %> </td>
      <td><%= link_to 'Show', article_path(article.id) %></td>
      <% if logged_in? && article.user == current_user %>
        <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
        <td><%= link_to 'Delete', article_path(article.id), method: :delete, data: {turbo_confirm: "Are you Sure?", turbo_method: :delete} %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>

</table>

Rails_Projects/alpha-blog/app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %><br/>
  </p>

<% end %>

Rails_Projects/alpha-blog/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel & Return', articles_path %>

Rails_Projects/alpha-blog/app/views/articles/index.html.erb
<h1>Listing all articles</h1>


<div>
  <%= will_paginate @articles, :container => false %>
</div>


<%= render 'article' %>

<div>
  <%= will_paginate @articles, :container => false %>
</div>

<p>
<%= link_to 'Create New Article', new_article_path %>
</p>

Rails_Projects/alpha-blog/app/views/articles/new.html.erb
<h1>Create New article</h1>

<%= render 'form' %>

<%= link_to 'Return to Articles page', articles_path %>

Rails_Projects/alpha-blog/app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>Written by: </strong><%= link_to @article.user.username, user_path(@article.user) %></p>

<% if logged_in? && @article.user == current_user %>
    <%= link_to 'Edit', edit_article_path(@article) %>
    <%= link_to 'Delete', article_path(@article.id), method: :delete, data: {turbo_confirm: "Are you Sure?", turbo_method: :delete} %>
<% end %>
<%= link_to 'Return to Articles Homepage', articles_path %>

Rails_Projects/alpha-blog/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

Rails_Projects/alpha-blog/app/views/layouts/_navigation.html.erb
<html>
<head>
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #111;
}
</style>
</head>
<body>

<ul>
  <li><%= link_to 'BLOG', root_path %></li>
  <li><%= link_to 'View Articles', articles_path %></li>
  <li><%= link_to 'View Users', users_path %></li>
  <% if logged_in? %>
    <li><%= link_to 'Create Article', new_article_path %></li>
    <li><%= link_to 'View profile', user_path(current_user.id) %></li>
    <li><%= link_to 'Edit profile', edit_user_path(current_user.id) %></li>
    <li><%= link_to 'Delete profile', user_path(current_user.id), method: :delete, data: {turbo_confirm: "Are you Sure?", turbo_method: :delete} %></li>
    <li><%= button_to 'Logout', logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Log in', login_path %></li>
    <li><%= link_to "Sign up!", signup_path %></li>
  <% end %>
</ul>

</body>
</html>

Rails_Projects/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href = "https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

Rails_Projects/alpha-blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

Rails_Projects/alpha-blog/app/views/users/_form.html.erb
<div>
  <div>
    <div>
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, local: true) do |f| %>
        <div>
          <%= f.label :username %>
          <div>
            <%= f.text_field :username, placeholder: "Enter a username" %>
          </div>
        </div>

        <div>
          <%= f.label :f_name %>
          <div>
            <%= f.text_field :f_name, placeholder: "Enter first name" %>
          </div>
        </div>

        <div>
          <%= f.label :l_name %>
          <div>
            <%= f.text_field :l_name, placeholder: "Enter last name" %>
          </div>
        </div>

        <div>
          <%= f.label :email %>
          <div> 
            <%= f.email_field :email, placeholder: "Enter your email address" %>
          </div>
        </div>

        <div>
          <%= f.label :password %>
          <div> 
            <%= f.password_field :password, placeholder: "Choose a password" %>
          </div>
        </div>

        <div>
          <%= f.label :avatar, style: "display: block" %>
          <%= f.file_field :avatar %>
        </div>

        <div>
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>



      <% end %>
    </div>
    <div>
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

Rails_Projects/alpha-blog/app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

<%= link_to 'Cancel & Return', articles_path %>

Rails_Projects/alpha-blog/app/views/users/index.html.erb
<h1>Blog Users</h1>

<div>
  <%= will_paginate @users, :container => false %>
</div>

<table>

  <thead>
    <tr>
      <th>Username</th>
      <th>Total Articles Written</th>
      <th colspan="1">Actions</th>
      <th>Joined</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>

    <tr>
      <td> <%= link_to user.username, user %> </td>
      <td> <%= pluralize(user.articles.count, 'article') %> </td>
      <td><%= link_to 'View', user %></td>
      <% if logged_in? && user == current_user %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <% end %>
      <td><%= time_ago_in_words(user.created_at) %> ago</td>
    </tr>
    <% end %>
  </tbody>

</table>

<div>
  <%= will_paginate @users, :container => false %>
</div>

Rails_Projects/alpha-blog/app/views/users/new.html.erb
<h1>Sign up for Blog</h1>

<%= render 'form' %>

Rails_Projects/alpha-blog/app/views/users/show.html.erb
<h1> <%= @user.username %>'s profile </h1>
<img src= <%= @user.avatar %> alt=""/>


<% if logged_in? && @user == current_user %>
    <div class = 'text-center mt-4'><%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-outline-info" %></div>
<% end %>

<h1>Articles</h1>

<%= render 'articles/article' %>