Rails_Projects/foodlog/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'archives/index'
  get 'archive/index'
  resources :entries
  root to: "entries#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Rails_Projects/foodlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Rails_Projects/foodlog/app/models/category.rb
class Category < ApplicationRecord
    has_many :entries
end

Rails_Projects/foodlog/app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :category

    # validates ${:calories, :proteins, :carbs, :fats, :meal_type}, presence :true
    validates :meal_type, presence: true
    validates :calories, presence: true
    validates :proteins, presence: true
    validates :carbs, presence: true
    validates :fats, presence: true

    def day
        self.created_at.strftime("%b %e, %Y")
    end

end

Rails_Projects/foodlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rails_Projects/foodlog/app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

Rails_Projects/foodlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

Rails_Projects/foodlog/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbs, :fats, :category)
    end
end

Rails_Projects/foodlog/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails_Projects/foodlog/app/helpers/archives_helper.rb
module ArchivesHelper
end

Rails_Projects/foodlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

Rails_Projects/foodlog/app/helpers/entries_helper.rb
module EntriesHelper
end

Rails_Projects/foodlog/app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-half">
        <% @entries.each do |day, entries| %>
            <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">Entries for <%= day %></h3>

            <nav class="level is-mobile">
                <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Calories</p>
                    <p class="title"><%= entries.pluck(:calories).sum %></p>
                </div>
                </div>
                <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Protein</p>
                    <p class="title"><%= entries.pluck(:proteins).sum %>g</p>
                </div>
                </div>
                <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Carbs</p>
                    <p class="title"><%= entries.pluck(:carbs).sum %>g</p>
                </div>
                </div>
                <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Fats</p>
                    <p class="title"><%= entries.pluck(:fats).sum %>g</p>
                </div>
                </div>
            </nav>

            <% entries.each do |entry| %>
                <%= link_to entry_path(entry) do %>
                    <div class="card">
                        <div class="card-content">
                            <strong><%= entry.meal_type %></strong><br/>
                            <%= entry.calories %> calories,
                            <%= entry.proteins %> g proteins,
                            <%= entry.carbs %> g carbs,
                            <%= entry.fats %> g fats,
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>

    </div>
</div>

Rails_Projects/foodlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <% if notice.present? %>
      <div class="notification is-link is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

Rails_Projects/foodlog/app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
            <%= link_to root_path, class: "navbar-item" do %>
                <span class="has-textweight-bold is-size-4 ml-4">FoodLog</span>
            <% end %>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
            <%= link_to new_entry_path, class: "button is-success" do %>
                <span>Create new entry</span>
            <% end %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for(:title) %>
            <%= yield :title %>
        <% else %>
            Foodlog
        <% end %>
      </p>
    </div>
  </div>


</section>